[project]
dependencies = [
  "beautifulsoup4>=4.13.4",
  "brotli>=1.1.0",
  "flask>=3.1.1",
  "lxml>=6.0.0",
  "requests>=2.32.4",
]
description = "Add your description here"
name = "apple-fitness-filter"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"
